#!/bin/bash
#PBS -P CFP01-CF-060
#PBS -j oe
#PBS -k oed
#PBS -N vllm_server
#PBS -q auto
#PBS -l select=1:ngpus=8
#PBS -l walltime=56:00:00

cd $PBS_O_WORKDIR

image="/app1/common/singularity-img/hopper/cuda/cuda_12.1.0-cudnn8-devel-u20.04.sif"
module load singularity

singularity exec -e \
--env HF_HOME=/scratch/e1583535/cache \
--env HF_DATASETS_CACHE=/scratch/e1583535/cache/datasets \
$image bash << EOF > /scratch/e1583535/SEA-HELM-outputs/logs/server/stdout.$PBS_JOBID 2> /scratch/e1583535/SEA-HELM-outputs/logs/server/stderr.$PBS_JOBID

if [ -d "/hpctmp/e1583535/virtualenvs/sea-helm" ]; then
    source /hpctmp/e1583535/virtualenvs/sea-helm/bin/activate
fi

vllm serve \
/scratch/e1583535/llm/meta-llama/Llama-3.1-8B-Instruct \
--dtype bfloat16 \
--api-key 12345678 \
--tensor-parallel-size 8 \
--enable-prefix-caching

EOF